version: '3'
services:
  spire-server:
    image: ghcr.io/spiffe/spire-server:1.5.1
    hostname: spire-server
    volumes:
      - ./server:/opt/spire/conf/server
    command: ["-config", "/opt/spire/conf/server/server.conf"]
  spire-agent:
    image: ghcr.io/spiffe/spire-agent:1.5.1
    hostname: spire-agent
    volumes:
      - ./agent:/opt/spire/conf/agent
      - /var/run:/var/run
    depends_on: ["spire-server"]
    command: ["-config", "/opt/spire/conf/agent/agent.conf"]
